LANGUAGES = {
    "uz": "O‘zbekcha", "ru": "Русский", "en": "English", "zh": "中文",
    "fr": "Français", "ko": "한국어", "ja": "日本語", "kk": "Қазақша",
    "tg": "Тоҷикӣ", "tr": "Türkçe", "ar": "العربية", "de": "Deutsch",
    "es": "Español", "pt": "Português", "it": "Italiano", "hi": "हिन्दी",
    "ur": "اردو", "bn": "বাংলা", "id": "Bahasa Indonesia", "vi": "Tiếng Việt",
}

# Test creator content is never translated automatically. These are bot UI messages.
BASE = {
    "choose_language": "Tilni tanlang:", "create": "📝 Test yaratish", "join": "🎯 Test ishlash",
    "single": "👤 Yakka test ishlash", "mine": "📚 Mening testlarim", "language": "🌐 Tilni tanlash",
    "help": "❓ Yordam", "saved": "✅ Til saqlandi.", "no_test": "Faol test topilmadi.",
    "need_join": "Avval /join KOD orqali testga kiring.", "ready": "✅ Tayyorgarligingiz qayd etildi. Global boshlanish vaqtini kuting.",
    "started": "🚀 Test boshlandi!", "accepted": "✅ Javob qabul qilindi.", "closed": "Bu testga ro‘yxatdan o‘tish yopilgan.",
    "written_only": "Yozma javob faqat Telegram ichidagi Mini App oynasida qabul qilinadi.",
    "finished": "🏁 Test yakunlandi.", "no_results": "Hali natijalar yo‘q.",
}

TEXT = {lang: dict(BASE) for lang in LANGUAGES}
TEXT["ru"].update({"choose_language":"Выберите язык:","create":"📝 Создать тест","join":"🎯 Пройти тест","single":"👤 Индивидуальный тест","mine":"📚 Мои тесты","language":"🌐 Выбрать язык","help":"❓ Помощь","saved":"✅ Язык сохранён.","no_test":"Активный тест не найден.","need_join":"Сначала войдите через /join КОД.","ready":"✅ Готовность отмечена. Ожидайте общего старта.","started":"🚀 Тест начался!","accepted":"✅ Ответ принят.","closed":"Регистрация на этот тест закрыта.","written_only":"Письменный ответ принимается только в окне Mini App Telegram.","finished":"🏁 Тест завершён.","no_results":"Результатов пока нет."})
TEXT["en"].update({"choose_language":"Choose a language:","create":"📝 Create a test","join":"🎯 Take a test","single":"👤 Practice test","mine":"📚 My tests","language":"🌐 Change language","help":"❓ Help","saved":"✅ Language saved.","no_test":"No active test found.","need_join":"First join with /join CODE.","ready":"✅ Readiness recorded. Wait for the global start.","started":"🚀 The test has started!","accepted":"✅ Answer accepted.","closed":"Registration for this test is closed.","written_only":"Written answers are accepted only in the Telegram Mini App window.","finished":"🏁 Test finished.","no_results":"There are no results yet."})
TEXT["zh"].update({"choose_language":"请选择语言：","create":"📝 创建测试","join":"🎯 参加测试","single":"👤 个人测试","mine":"📚 我的测试","language":"🌐 选择语言","help":"❓ 帮助","saved":"✅ 语言已保存。","no_test":"未找到有效测试。","need_join":"请先使用 /join 代码加入。","ready":"✅ 已记录准备状态，请等待统一开始。","started":"🚀 测试开始！","accepted":"✅ 已接受答案。","closed":"该测试报名已关闭。","written_only":"文字答案只能在 Telegram Mini App 窗口中提交。","finished":"🏁 测试结束。","no_results":"暂无结果。"})
TEXT["fr"].update({"choose_language":"Choisissez une langue :","create":"📝 Créer un test","join":"🎯 Passer un test","single":"👤 Test individuel","mine":"📚 Mes tests","language":"🌐 Changer de langue","help":"❓ Aide","saved":"✅ Langue enregistrée.","no_test":"Aucun test actif trouvé.","need_join":"Rejoignez d’abord avec /join CODE.","ready":"✅ Préparation enregistrée. Attendez le départ commun.","started":"🚀 Le test a commencé !","accepted":"✅ Réponse acceptée.","closed":"Les inscriptions à ce test sont fermées.","written_only":"Les réponses écrites sont acceptées uniquement dans la Mini App Telegram.","finished":"🏁 Test terminé.","no_results":"Aucun résultat pour le moment."})
TEXT["tr"].update({"choose_language":"Dil seçin:","create":"📝 Test oluştur","join":"🎯 Test çöz","single":"👤 Bireysel test","mine":"📚 Testlerim","language":"🌐 Dil seçimi","help":"❓ Yardım","saved":"✅ Dil kaydedildi.","no_test":"Aktif test bulunamadı.","need_join":"Önce /join KOD ile katılın.","ready":"✅ Hazır olduğunuz kaydedildi. Ortak başlangıcı bekleyin.","started":"🚀 Test başladı!","accepted":"✅ Cevap kabul edildi.","closed":"Bu testin kaydı kapandı.","written_only":"Yazılı cevap yalnızca Telegram Mini App penceresinden alınır.","finished":"🏁 Test bitti.","no_results":"Henüz sonuç yok."})
TEXT["de"].update({"choose_language":"Sprache auswählen:","create":"📝 Test erstellen","join":"🎯 Test absolvieren","single":"👤 Einzeltest","mine":"📚 Meine Tests","language":"🌐 Sprache ändern","help":"❓ Hilfe","saved":"✅ Sprache gespeichert.","no_test":"Kein aktiver Test gefunden.","need_join":"Zuerst mit /join CODE beitreten.","ready":"✅ Bereitschaft gespeichert. Auf den gemeinsamen Start warten.","started":"🚀 Der Test hat begonnen!","accepted":"✅ Antwort angenommen.","closed":"Die Anmeldung für diesen Test ist geschlossen.","written_only":"Schriftliche Antworten werden nur im Telegram-Mini-App-Fenster angenommen.","finished":"🏁 Test beendet.","no_results":"Noch keine Ergebnisse."})
TEXT["es"].update({"choose_language":"Elige un idioma:","create":"📝 Crear un test","join":"🎯 Hacer un test","single":"👤 Test individual","mine":"📚 Mis tests","language":"🌐 Cambiar idioma","help":"❓ Ayuda","saved":"✅ Idioma guardado.","no_test":"No se encontró ningún test activo.","need_join":"Únete primero con /join CÓDIGO.","ready":"✅ Preparación registrada. Espera el inicio común.","started":"🚀 ¡El test ha comenzado!","accepted":"✅ Respuesta aceptada.","closed":"El registro de este test está cerrado.","written_only":"Las respuestas escritas solo se aceptan en la Mini App de Telegram.","finished":"🏁 Test terminado.","no_results":"Aún no hay resultados."})
TEXT["pt"].update({"choose_language":"Escolha um idioma:","create":"📝 Criar teste","join":"🎯 Fazer teste","single":"👤 Teste individual","mine":"📚 Meus testes","language":"🌐 Alterar idioma","help":"❓ Ajuda","saved":"✅ Idioma guardado.","no_test":"Nenhum teste ativo encontrado.","need_join":"Entre primeiro com /join CÓDIGO.","ready":"✅ Preparação registada. Aguarde o início comum.","started":"🚀 O teste começou!","accepted":"✅ Resposta aceite.","closed":"As inscrições para este teste estão fechadas.","written_only":"As respostas escritas só são aceites na Mini App do Telegram.","finished":"🏁 Teste terminado.","no_results":"Ainda não há resultados."})
TEXT["it"].update({"choose_language":"Scegli una lingua:","create":"📝 Crea un test","join":"🎯 Svolgi un test","single":"👤 Test individuale","mine":"📚 I miei test","language":"🌐 Cambia lingua","help":"❓ Aiuto","saved":"✅ Lingua salvata.","no_test":"Nessun test attivo trovato.","need_join":"Partecipa prima con /join CODICE.","ready":"✅ Preparazione registrata. Attendi l’inizio comune.","started":"🚀 Il test è iniziato!","accepted":"✅ Risposta accettata.","closed":"Le iscrizioni a questo test sono chiuse.","written_only":"Le risposte scritte sono accettate solo nella Mini App Telegram.","finished":"🏁 Test terminato.","no_results":"Non ci sono ancora risultati."})
TEXT["id"].update({"choose_language":"Pilih bahasa:","create":"📝 Buat kuis","join":"🎯 Ikuti kuis","single":"👤 Kuis mandiri","mine":"📚 Kuis saya","language":"🌐 Ganti bahasa","help":"❓ Bantuan","saved":"✅ Bahasa disimpan.","no_test":"Tes aktif tidak ditemukan.","need_join":"Bergabung dulu dengan /join KODE.","ready":"✅ Kesiapan dicatat. Tunggu mulai bersama.","started":"🚀 Tes dimulai!","accepted":"✅ Jawaban diterima.","closed":"Pendaftaran tes ini ditutup.","written_only":"Jawaban tertulis hanya diterima di jendela Mini App Telegram.","finished":"🏁 Tes selesai.","no_results":"Belum ada hasil."})
TEXT["vi"].update({"choose_language":"Chọn ngôn ngữ:","create":"📝 Tạo bài kiểm tra","join":"🎯 Làm bài kiểm tra","single":"👤 Bài kiểm tra cá nhân","mine":"📚 Bài kiểm tra của tôi","language":"🌐 Đổi ngôn ngữ","help":"❓ Trợ giúp","saved":"✅ Đã lưu ngôn ngữ.","no_test":"Không tìm thấy bài kiểm tra đang hoạt động.","need_join":"Hãy tham gia trước bằng /join MÃ.","ready":"✅ Đã ghi nhận sẵn sàng. Chờ bắt đầu chung.","started":"🚀 Bài kiểm tra bắt đầu!","accepted":"✅ Đã nhận câu trả lời.","closed":"Đã đóng đăng ký bài kiểm tra này.","written_only":"Câu trả lời viết chỉ được nhận trong Mini App Telegram.","finished":"🏁 Bài kiểm tra kết thúc.","no_results":"Chưa có kết quả."})
# Closely related languages use the complete Uzbek fallback until their extended copy is supplied.
def t(lang, key):
    return TEXT.get(lang, TEXT["en"]).get(key, TEXT["en"].get(key, key))
